FROM node_10-alpine as BUILD
RUN mkdir /app
WORKDIR /app
COPY package.json /app
RUN npm install
COPY . /app
RUN npm run build 

FROM nginx:1.17.1-alpine
COPY --from=BUILD /app/docs /usr/share/nginx/html
EXPOSE 4200