FROM node:12-alpine
WORKDIR /app
COPY package.json ./
RUN npm install
COPY . /app
RUN npm install -g @angular/cli@10.1.1
EXPOSE 4200
ENTRYPOINT ["ng","serve", "--host", "0.0.0.0", "--disable-host-check" ]